// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace JekyllWriter
{
	public partial class MainWindowController : NSWindowController
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

        public override void WindowDidLoad()
        {
            base.WindowDidLoad();

            // Set window to use Full Size Content View
            //Window.StyleMask = NSWindowStyle.Closable;
        }
	}
}
